export const GET_MOVIES = "GET_MOVIES";
export const GET_FAVOURITES = "GET_FAVOURITES";
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const FAILED_ADD_FAVOURITE = "FAILED_ADD_FAVOURITE";

export const UPDATE_FETCH_PHRASE__START = "UPDATE_FETCH_PHRASE__START";
export const UPDATE_FETCH_PHRASE__SUCCESS = "UPDATE_FETCH_PHRASE__SUCCESS";
export const UPDATE_FETCH_PHRASE__FAILURE = "UPDATE_FETCH_PHRASE__FAILURE";
